// <auto-generated />
using System;
using System.Collections.Generic;
using Guild.Domain.Enums;
using Guild.Persistence.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Guild.Persistence.Migrations
{
    [DbContext(typeof(MicroserviceContext))]
    [Migration("20260519170802_AddWebhookConfigs")]
    partial class AddWebhookConfigs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "channel_type", new[] { "announcement", "forum", "text", "ticket", "voice" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "encryption_state", new[] { "encrypted", "encrypted_without_fallback_key", "plain" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "invite_state", new[] { "active", "expired" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "invite_type", new[] { "one_time", "permanent" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "member_type", new[] { "bot", "default", "persona" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "permission_state", new[] { "allow", "deny", "inherit" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "role_type", new[] { "everyone", "none" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "wiki_visibility", new[] { "private", "public" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Guild.Domain.Aggregates.Channel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CategoryId")
                        .HasColumnType("text")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<EncryptionState>("EncryptionState")
                        .HasColumnType("encryption_state")
                        .HasColumnName("encryption_state");

                    b.Property<string>("GuildId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("guild_id");

                    b.Property<bool>("IsAgeRestricted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_age_restricted");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_private");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<ChannelType>("Type")
                        .HasColumnType("channel_type")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_channels");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_channels_category_id");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("ix_channels_guild_id");

                    b.ToTable("channels", (string)null);
                });

            modelBuilder.Entity("Guild.Domain.Aggregates.Guild", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<EncryptionState>("EncryptionState")
                        .HasColumnType("encryption_state")
                        .HasColumnName("encryption_state");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.Property<string>("SystemChannelId")
                        .HasColumnType("text")
                        .HasColumnName("system_channel_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_guilds");

                    b.HasIndex("SystemChannelId")
                        .IsUnique()
                        .HasDatabaseName("ix_guilds_system_channel_id");

                    b.ToTable("guilds", (string)null);
                });

            modelBuilder.Entity("Guild.Domain.Aggregates.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("GuildId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("guild_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Permissions")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("permissions");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<RoleType>("Type")
                        .HasColumnType("role_type")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("ix_roles_guild_id");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Guild.Domain.Entity.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GuildId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("guild_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("ix_categories_guild_id");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Guild.Domain.Entity.ChannelPermission", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<decimal>("AllowPermissions")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("allow_permissions");

                    b.Property<string>("CategoryId")
                        .HasColumnType("text")
                        .HasColumnName("category_id");

                    b.Property<string>("ChannelId")
                        .HasColumnType("text")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DenyPermissions")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("deny_permissions");

                    b.Property<string>("MemberId")
                        .HasColumnType("text")
                        .HasColumnName("member_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_channel_permissions");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_channel_permissions_category_id_filtered")
                        .HasFilter("category_id IS NOT NULL");

                    b.HasIndex("ChannelId")
                        .HasDatabaseName("IX_channel_permissions_channel_id_filtered")
                        .HasFilter("channel_id IS NOT NULL");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_channel_permissions_member_id");

                    b.HasIndex("RoleId", "MemberId")
                        .HasDatabaseName("IX_channel_permissions_role_member");

                    b.ToTable("channel_permissions", (string)null);
                });

            modelBuilder.Entity("Guild.Domain.Entity.GuildInvite", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GuildId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("guild_id");

                    b.Property<InviteState>("State")
                        .HasColumnType("invite_state")
                        .HasColumnName("state");

                    b.Property<InviteType>("Type")
                        .HasColumnType("invite_type")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_guild_invites");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("ix_guild_invites_guild_id");

                    b.ToTable("guild_invites", (string)null);
                });

            modelBuilder.Entity("Guild.Domain.Entity.GuildMember", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<decimal>("AllowPermissions")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("allow_permissions");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DenyPermissions")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("deny_permissions");

                    b.Property<string>("GuildId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("guild_id");

                    b.Property<string>("InviteId")
                        .HasColumnType("text")
                        .HasColumnName("invite_id");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Nickname")
                        .HasColumnType("text")
                        .HasColumnName("nickname");

                    b.Property<string>("SearchValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_value");

                    b.Property<MemberType>("Type")
                        .HasColumnType("member_type")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_guild_members");

                    b.HasIndex("InviteId")
                        .HasDatabaseName("ix_guild_members_invite_id");

                    b.HasIndex("GuildId", "UserId")
                        .HasDatabaseName("ix_guild_members_guild_id_user_id");

                    b.ToTable("guild_members", (string)null);
                });

            modelBuilder.Entity("Guild.Domain.Entity.PublicKeyStore", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ChannelId")
                        .HasColumnType("text")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GuildId")
                        .HasColumnType("text")
                        .HasColumnName("guild_id");

                    b.Property<byte[]>("Key")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_public_keys");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("ix_public_keys_guild_id");

                    b.ToTable("public_keys", (string)null);
                });

            modelBuilder.Entity("Guild.Domain.Entity.ReadState", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ChannelId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LastReadMessageId")
                        .HasColumnType("text")
                        .HasColumnName("last_read_message_id");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("member_id");

                    b.Property<int>("MentionCount")
                        .HasColumnType("integer")
                        .HasColumnName("mention_count");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_read_states");

                    b.HasIndex("ChannelId")
                        .HasDatabaseName("ix_read_states_channel_id");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_read_states_member_id");

                    b.ToTable("read_states", (string)null);
                });

            modelBuilder.Entity("Guild.Domain.Entity.RoleMember", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("member_id");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_role_members");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_role_members_member_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_members_role_id");

                    b.ToTable("role_members", (string)null);
                });

            modelBuilder.Entity("Guild.Domain.Entity.WebhookConfig", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("GuildId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("guild_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_webhook_configs");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("ix_webhook_configs_guild_id");

                    b.ToTable("webhook_configs", (string)null);
                });

            modelBuilder.Entity("Guild.Domain.Entity.Wiki", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GuildId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("guild_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_wikis");

                    b.HasIndex("GuildId")
                        .IsUnique()
                        .HasDatabaseName("ix_wikis_guild_id");

                    b.ToTable("wikis", (string)null);
                });

            modelBuilder.Entity("Guild.Domain.Entity.WikiCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GuildId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("guild_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ParentCategoryId")
                        .HasColumnType("text")
                        .HasColumnName("parent_category_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_wiki_categories");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("ix_wiki_categories_guild_id");

                    b.ToTable("wiki_categories", (string)null);
                });

            modelBuilder.Entity("Guild.Domain.Entity.WikiPage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author_id");

                    b.Property<string>("CategoryId")
                        .HasColumnType("text")
                        .HasColumnName("category_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GuildId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("guild_id");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_pinned");

                    b.Property<string>("LastEditorId")
                        .HasColumnType("text")
                        .HasColumnName("last_editor_id");

                    b.Property<string>("ParentPageId")
                        .HasColumnType("text")
                        .HasColumnName("parent_page_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<WikiVisibility>("Visibility")
                        .HasColumnType("wiki_visibility")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_wiki_pages");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("ix_wiki_pages_guild_id");

                    b.ToTable("wiki_pages", (string)null);
                });

            modelBuilder.Entity("Guild.Domain.Entity.WikiRevision", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EditorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("editor_id");

                    b.Property<string>("PageId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("page_id");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("revision_number");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_wiki_revisions");

                    b.HasIndex("PageId")
                        .HasDatabaseName("ix_wiki_revisions_page_id");

                    b.ToTable("wiki_revisions", (string)null);
                });

            modelBuilder.Entity("Guild.Domain.Aggregates.Channel", b =>
                {
                    b.HasOne("Guild.Domain.Entity.Category", "Category")
                        .WithMany("Channels")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_channels_categories_category_id");

                    b.HasOne("Guild.Domain.Aggregates.Guild", "Guild")
                        .WithMany("Channels")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_channels_guilds_guild_id");

                    b.Navigation("Category");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Guild.Domain.Aggregates.Guild", b =>
                {
                    b.HasOne("Guild.Domain.Aggregates.Channel", "SystemChannel")
                        .WithOne("SystemChannelGuild")
                        .HasForeignKey("Guild.Domain.Aggregates.Guild", "SystemChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_guilds_channels_system_channel_id");

                    b.Navigation("SystemChannel");
                });

            modelBuilder.Entity("Guild.Domain.Aggregates.Role", b =>
                {
                    b.HasOne("Guild.Domain.Aggregates.Guild", "Guild")
                        .WithMany("Roles")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roles_guilds_guild_id");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Guild.Domain.Entity.Category", b =>
                {
                    b.HasOne("Guild.Domain.Aggregates.Guild", "Guild")
                        .WithMany("Categories")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_categories_guilds_guild_id");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Guild.Domain.Entity.ChannelPermission", b =>
                {
                    b.HasOne("Guild.Domain.Entity.Category", "Category")
                        .WithMany("Permissions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_channel_permissions_categories_category_id");

                    b.HasOne("Guild.Domain.Aggregates.Channel", "Channel")
                        .WithMany("Permissions")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_channel_permissions_channels_channel_id");

                    b.HasOne("Guild.Domain.Entity.GuildMember", "Member")
                        .WithMany("PermissionOverwrites")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_channel_permissions_guild_members_member_id");

                    b.HasOne("Guild.Domain.Aggregates.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_channel_permissions_roles_role_id");

                    b.Navigation("Category");

                    b.Navigation("Channel");

                    b.Navigation("Member");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Guild.Domain.Entity.GuildInvite", b =>
                {
                    b.HasOne("Guild.Domain.Aggregates.Guild", "Guild")
                        .WithMany("Invites")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guild_invites_guilds_guild_id");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Guild.Domain.Entity.GuildMember", b =>
                {
                    b.HasOne("Guild.Domain.Aggregates.Guild", "Guild")
                        .WithMany("Members")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guild_members_guilds_guild_id");

                    b.HasOne("Guild.Domain.Entity.GuildInvite", "Invite")
                        .WithMany("Members")
                        .HasForeignKey("InviteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_guild_members_guild_invites_invite_id");

                    b.Navigation("Guild");

                    b.Navigation("Invite");
                });

            modelBuilder.Entity("Guild.Domain.Entity.PublicKeyStore", b =>
                {
                    b.HasOne("Guild.Domain.Aggregates.Channel", null)
                        .WithMany("PublicKeys")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_public_keys_channels_guild_id");

                    b.HasOne("Guild.Domain.Aggregates.Guild", null)
                        .WithMany("PublicKeys")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_public_keys_guilds_guild_id");
                });

            modelBuilder.Entity("Guild.Domain.Entity.ReadState", b =>
                {
                    b.HasOne("Guild.Domain.Aggregates.Channel", "Channel")
                        .WithMany("ReadStates")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_read_states_channels_channel_id");

                    b.HasOne("Guild.Domain.Entity.GuildMember", "GuildMember")
                        .WithMany("ReadStates")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_read_states_guild_members_member_id");

                    b.Navigation("Channel");

                    b.Navigation("GuildMember");
                });

            modelBuilder.Entity("Guild.Domain.Entity.RoleMember", b =>
                {
                    b.HasOne("Guild.Domain.Entity.GuildMember", "Member")
                        .WithMany("RoleMembers")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_members_guild_members_member_id");

                    b.HasOne("Guild.Domain.Aggregates.Role", "Role")
                        .WithMany("Members")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_members_roles_role_id");

                    b.Navigation("Member");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Guild.Domain.Entity.WebhookConfig", b =>
                {
                    b.HasOne("Guild.Domain.Aggregates.Guild", "Guild")
                        .WithMany("WebhookConfigs")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_webhook_configs_guilds_guild_id");

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Guild.Domain.Entity.Wiki", b =>
                {
                    b.HasOne("Guild.Domain.Aggregates.Guild", null)
                        .WithOne()
                        .HasForeignKey("Guild.Domain.Entity.Wiki", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wikis_guilds_guild_id");
                });

            modelBuilder.Entity("Guild.Domain.Entity.WikiCategory", b =>
                {
                    b.HasOne("Guild.Domain.Aggregates.Guild", null)
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wiki_categories_guilds_guild_id");
                });

            modelBuilder.Entity("Guild.Domain.Entity.WikiPage", b =>
                {
                    b.HasOne("Guild.Domain.Aggregates.Guild", null)
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wiki_pages_guilds_guild_id");
                });

            modelBuilder.Entity("Guild.Domain.Entity.WikiRevision", b =>
                {
                    b.HasOne("Guild.Domain.Entity.WikiPage", null)
                        .WithMany("Revisions")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wiki_revisions_wiki_pages_page_id");
                });

            modelBuilder.Entity("Guild.Domain.Aggregates.Channel", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("PublicKeys");

                    b.Navigation("ReadStates");

                    b.Navigation("SystemChannelGuild");
                });

            modelBuilder.Entity("Guild.Domain.Aggregates.Guild", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Channels");

                    b.Navigation("Invites");

                    b.Navigation("Members");

                    b.Navigation("PublicKeys");

                    b.Navigation("Roles");

                    b.Navigation("WebhookConfigs");
                });

            modelBuilder.Entity("Guild.Domain.Aggregates.Role", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Guild.Domain.Entity.Category", b =>
                {
                    b.Navigation("Channels");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Guild.Domain.Entity.GuildInvite", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Guild.Domain.Entity.GuildMember", b =>
                {
                    b.Navigation("PermissionOverwrites");

                    b.Navigation("ReadStates");

                    b.Navigation("RoleMembers");
                });

            modelBuilder.Entity("Guild.Domain.Entity.WikiPage", b =>
                {
                    b.Navigation("Revisions");
                });
#pragma warning restore 612, 618
        }
    }
}
