// <auto-generated />
using System;
using Messaging.Domain.Enums;
using Messaging.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Messaging.Infrastructure.Migrations
{
    [DbContext(typeof(MicroserviceContext))]
    [Migration("20260510155143_mls")]
    partial class mls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "attachment_state", new[] { "complete", "pending" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "channel_encryption_state", new[] { "encrypted", "plain" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "message_type", new[] { "guild_member_join", "guild_member_leave", "invite", "message" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Messaging.Domain.Aggregates.Conversation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<ChannelEncryptionState>("EncryptionState")
                        .HasColumnType("channel_encryption_state")
                        .HasColumnName("encryption_state");

                    b.Property<long?>("MlsEpoch")
                        .HasColumnType("bigint")
                        .HasColumnName("mls_epoch");

                    b.Property<byte[]>("MlsGroupId")
                        .HasColumnType("bytea")
                        .HasColumnName("mls_group_id");

                    b.Property<byte[]>("MlsGroupInfo")
                        .HasColumnType("bytea")
                        .HasColumnName("mls_group_info");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_conversations");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("Messaging.Domain.Entities.Attachment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creator_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<AttachmentState>("State")
                        .HasColumnType("attachment_state")
                        .HasColumnName("state");

                    b.Property<string>("ThumbnailId")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_id");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_url");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_attachments");

                    b.ToTable("attachments", (string)null);
                });

            modelBuilder.Entity("Messaging.Domain.Entities.ConversationMember", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("CachedUserHash")
                        .HasColumnType("integer")
                        .HasColumnName("cached_user_hash");

                    b.Property<string>("CachedUserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cached_user_name");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LastReadMessageId")
                        .HasColumnType("text")
                        .HasColumnName("last_read_message_id");

                    b.Property<int>("MentionCount")
                        .HasColumnType("integer")
                        .HasColumnName("mention_count");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("public_key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_members");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("ix_members_conversation_id");

                    b.ToTable("members", (string)null);
                });

            modelBuilder.Entity("Messaging.Domain.Entities.ConversationMemberDevice", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConversationMemberId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conversation_member_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<int>("MlsLeafIndex")
                        .HasColumnType("integer")
                        .HasColumnName("mls_leaf_index");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_member_devices");

                    b.HasIndex("ConversationMemberId")
                        .HasDatabaseName("ix_member_devices_conversation_member_id");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ix_member_devices_device_id");

                    b.ToTable("member_devices", (string)null);
                });

            modelBuilder.Entity("Messaging.Domain.Entities.ConversationMember", b =>
                {
                    b.HasOne("Messaging.Domain.Aggregates.Conversation", "Conversation")
                        .WithMany("Members")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_members_conversations_conversation_id");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Messaging.Domain.Entities.ConversationMemberDevice", b =>
                {
                    b.HasOne("Messaging.Domain.Entities.ConversationMember", "ConversationMember")
                        .WithMany("Devices")
                        .HasForeignKey("ConversationMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_member_devices_members_conversation_member_id");

                    b.Navigation("ConversationMember");
                });

            modelBuilder.Entity("Messaging.Domain.Aggregates.Conversation", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Messaging.Domain.Entities.ConversationMember", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
