// <auto-generated />
using System;
using Bots.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bots.Infrastructure.Migrations
{
    [DbContext(typeof(MicroserviceContext))]
    partial class MicroserviceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bots.Domain.Entity.BotApplication", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("BotUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bot_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DefaultPermissions")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("default_permissions");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("IconUrl")
                        .HasColumnType("text")
                        .HasColumnName("icon_url");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_bot_applications");

                    b.HasIndex("BotUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_bot_applications_bot_user_id");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_bot_applications_owner_user_id");

                    b.ToTable("bot_applications", (string)null);
                });

            modelBuilder.Entity("Bots.Domain.Entity.BotInstallation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("BotApplicationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bot_application_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("GrantedPermissions")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("granted_permissions");

                    b.Property<string>("GuildId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("guild_id");

                    b.Property<string>("GuildMemberId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("guild_member_id");

                    b.Property<DateTimeOffset>("InstalledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("installed_at");

                    b.Property<string>("InstalledByUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("installed_by_user_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_bot_installations");

                    b.HasIndex("BotApplicationId", "GuildId")
                        .IsUnique()
                        .HasDatabaseName("ix_bot_installations_bot_application_id_guild_id");

                    b.ToTable("bot_installations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
