// <auto-generated />
using System;
using Federation.Domain.Events;
using Federation.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Federation.Infrastructure.Migrations
{
    [DbContext(typeof(MicroserviceContext))]
    [Migration("20260520182803_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "federation_status", new[] { "active", "blocked", "defederated", "suspended" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Federation.Domain.Aggregates.FederatedGuild", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FederatedGuildId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("federated_guild_id");

                    b.Property<string>("InstanceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instance_id");

                    b.Property<string>("RemoteId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("remote_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_federated_guild");

                    b.HasIndex("InstanceId")
                        .HasDatabaseName("ix_federated_guild_instance_id");

                    b.ToTable("federated_guild", (string)null);
                });

            modelBuilder.Entity("Federation.Domain.Aggregates.FederationInstance", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefederationReason")
                        .HasColumnType("text")
                        .HasColumnName("defederation_reason");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("public_key");

                    b.Property<FederationStatus>("Status")
                        .HasColumnType("federation_status")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_federation_instances");

                    b.ToTable("federation_instances", (string)null);
                });

            modelBuilder.Entity("Federation.Domain.Aggregates.FederatedGuild", b =>
                {
                    b.HasOne("Federation.Domain.Aggregates.FederationInstance", "Instance")
                        .WithMany("FederatedGuilds")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_federated_guild_federation_instances_instance_id");

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("Federation.Domain.Aggregates.FederationInstance", b =>
                {
                    b.Navigation("FederatedGuilds");
                });
#pragma warning restore 612, 618
        }
    }
}
