// <auto-generated />
using System;
using Federation.Domain.Aggregates;
using Federation.Domain.Events;
using Federation.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Federation.Infrastructure.Migrations
{
    [DbContext(typeof(MicroserviceContext))]
    partial class MicroserviceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "acceptance_policy", new[] { "auto_accept", "require_approval" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "federated_resource_type", new[] { "conversation", "friendship", "guild" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "federation_status", new[] { "active", "blocked", "defederated", "pending", "suspended" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Federation.Domain.Aggregates.FederatedEventRecord", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("text")
                        .HasColumnName("event_id");

                    b.Property<bool>("Applied")
                        .HasColumnType("boolean")
                        .HasColumnName("applied");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<bool>("Delivered")
                        .HasColumnType("boolean")
                        .HasColumnName("delivered");

                    b.Property<long>("Depth")
                        .HasColumnType("bigint")
                        .HasColumnName("depth");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.PrimitiveCollection<string[]>("PreviousEventIds")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("previous_event_ids");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope_key");

                    b.Property<string>("TargetHost")
                        .HasColumnType("text")
                        .HasColumnName("target_host");

                    b.HasKey("EventId")
                        .HasName("pk_federated_events");

                    b.ToTable("federated_events", (string)null);
                });

            modelBuilder.Entity("Federation.Domain.Aggregates.FederatedResource", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("InstanceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("instance_id");

                    b.Property<string>("LocalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("local_id");

                    b.Property<string>("RemoteId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("remote_id");

                    b.Property<FederatedResourceType>("ResourceType")
                        .HasColumnType("federated_resource_type")
                        .HasColumnName("resource_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_federated_resources");

                    b.HasIndex("ResourceType", "LocalId")
                        .HasDatabaseName("ix_federated_resources_resource_type_local_id");

                    b.HasIndex("InstanceId", "ResourceType", "RemoteId")
                        .IsUnique()
                        .HasDatabaseName("ix_federated_resources_instance_id_resource_type_remote_id");

                    b.ToTable("federated_resources", (string)null);
                });

            modelBuilder.Entity("Federation.Domain.Aggregates.FederationInstance", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefederationReason")
                        .HasColumnType("text")
                        .HasColumnName("defederation_reason");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("public_key");

                    b.Property<FederationStatus>("Status")
                        .HasColumnType("federation_status")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_federation_instances");

                    b.HasIndex("Host")
                        .IsUnique()
                        .HasDatabaseName("ix_federation_instances_host");

                    b.ToTable("federation_instances", (string)null);
                });

            modelBuilder.Entity("Federation.Domain.Aggregates.FederationSettings", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<AcceptancePolicy>("AcceptancePolicy")
                        .HasColumnType("acceptance_policy")
                        .HasColumnName("acceptance_policy");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_federation_settings");

                    b.ToTable("federation_settings", (string)null);
                });

            modelBuilder.Entity("Federation.Domain.Aggregates.FederatedResource", b =>
                {
                    b.HasOne("Federation.Domain.Aggregates.FederationInstance", "Instance")
                        .WithMany("FederatedResources")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_federated_resources_federation_instances_instance_id");

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("Federation.Domain.Aggregates.FederationInstance", b =>
                {
                    b.Navigation("FederatedResources");
                });
#pragma warning restore 612, 618
        }
    }
}
