// <auto-generated />
using System;
using Billing.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Billing.Infrastructure.Migrations
{
    [DbContext(typeof(MicroserviceContext))]
    [Migration("20260815101344_AddCreditRenewalOptIn")]
    partial class AddCreditRenewalOptIn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Billing.Domain.Aggregates.CreditCampaign", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AlertThresholdPercent")
                        .HasColumnType("integer")
                        .HasColumnName("alert_threshold_percent");

                    b.Property<DateTimeOffset?>("AlertedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alerted_at");

                    b.Property<bool>("Automated")
                        .HasColumnType("boolean")
                        .HasColumnName("automated");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<long?>("DefaultIssuePoints")
                        .HasColumnType("bigint")
                        .HasColumnName("default_issue_points");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<long>("IssuedPoints")
                        .HasColumnType("bigint")
                        .HasColumnName("issued_points");

                    b.Property<int?>("LotLifetimeDays")
                        .HasColumnType("integer")
                        .HasColumnName("lot_lifetime_days");

                    b.Property<long?>("MaxPerUserPoints")
                        .HasColumnType("bigint")
                        .HasColumnName("max_per_user_points");

                    b.Property<DateTimeOffset?>("PausedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paused_at");

                    b.Property<string>("PausedBy")
                        .HasColumnType("text")
                        .HasColumnName("paused_by");

                    b.Property<DateTimeOffset?>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<long>("TotalBudgetPoints")
                        .HasColumnType("bigint")
                        .HasColumnName("total_budget_points");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_credit_campaigns");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_credit_campaigns_code");

                    b.ToTable("credit_campaigns", null, t =>
                        {
                            t.HasCheckConstraint("ck_credit_campaigns_within_budget", "total_budget_points > 0 AND issued_points >= 0 AND issued_points <= total_budget_points");
                        });
                });

            modelBuilder.Entity("Billing.Domain.Aggregates.CreditEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<string>("CampaignId")
                        .HasColumnType("text")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("GrantId")
                        .HasColumnType("text")
                        .HasColumnName("grant_id");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("LotId")
                        .HasColumnType("text")
                        .HasColumnName("lot_id");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_credit_entries");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_credit_entries_idempotency_key");

                    b.HasIndex("LotId")
                        .HasDatabaseName("ix_credit_entries_lot_id");

                    b.HasIndex("CampaignId", "UserId")
                        .HasDatabaseName("ix_credit_entries_campaign_id_user_id")
                        .HasFilter("campaign_id IS NOT NULL");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_credit_entries_user_id_created_at");

                    b.ToTable("credit_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_credit_entries_amount_sign", "(kind = 'Issue' AND amount > 0) OR (kind IN ('Spend', 'Expiry', 'Reversal') AND amount < 0) OR (kind = 'Adjustment' AND amount <> 0)");

                            t.HasCheckConstraint("ck_credit_entries_reason_required", "kind NOT IN ('Adjustment', 'Reversal') OR (reason IS NOT NULL AND btrim(reason) <> '')");
                        });
                });

            modelBuilder.Entity("Billing.Domain.Aggregates.CreditLot", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CampaignId")
                        .HasColumnType("text")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("ExpiryWarningSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_warning_sent_at");

                    b.Property<long>("OriginalAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("original_amount");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_credit_lots");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_credit_lots_expires_at");

                    b.HasIndex("ExpiresAt", "ExpiryWarningSentAt")
                        .HasDatabaseName("ix_credit_lots_expires_at_expiry_warning_sent_at")
                        .HasFilter("expiry_warning_sent_at IS NULL");

                    b.HasIndex("UserId", "ExpiresAt")
                        .HasDatabaseName("ix_credit_lots_user_id_expires_at");

                    b.ToTable("credit_lots", null, t =>
                        {
                            t.HasCheckConstraint("ck_credit_lots_amount_positive", "original_amount > 0");
                        });
                });

            modelBuilder.Entity("Billing.Domain.Aggregates.CreditWallet", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CachedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cached_at");

                    b.Property<long>("CachedBalance")
                        .HasColumnType("bigint")
                        .HasColumnName("cached_balance");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_credit_wallets");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_credit_wallets_user_id");

                    b.ToTable("credit_wallets", null, t =>
                        {
                            t.HasCheckConstraint("ck_credit_wallets_balance_not_negative", "cached_balance >= 0");
                        });
                });

            modelBuilder.Entity("Billing.Domain.Aggregates.EntitlementVersion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_kind");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_entitlement_versions");

                    b.HasIndex("SubjectKind", "SubjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_entitlement_versions_subject_kind_subject_id");

                    b.ToTable("entitlement_versions", (string)null);
                });

            modelBuilder.Entity("Billing.Domain.Aggregates.Grant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("EntitlementsJson")
                        .HasColumnType("text")
                        .HasColumnName("entitlements_json");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("GrantKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grant_kind");

                    b.Property<string>("Plan")
                        .HasColumnType("text")
                        .HasColumnName("plan");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("RevokeReason")
                        .HasColumnType("text")
                        .HasColumnName("revoke_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedBy")
                        .HasColumnType("text")
                        .HasColumnName("revoked_by");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset?>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_kind");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_grants");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_grants_expires_at")
                        .HasFilter("expires_at IS NOT NULL AND revoked_at IS NULL");

                    b.HasIndex("SubjectKind", "SubjectId")
                        .HasDatabaseName("ix_grants_subject_kind_subject_id");

                    b.ToTable("grants", (string)null);
                });

            modelBuilder.Entity("Billing.Domain.Aggregates.Plan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text")
                        .HasColumnName("archive_reason");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("ArchivedBy")
                        .HasColumnType("text")
                        .HasColumnName("archived_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int>("CurrentVersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("current_version_number");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<bool>("SeededFromConfiguration")
                        .HasColumnType("boolean")
                        .HasColumnName("seeded_from_configuration");

                    b.Property<string>("StripeProductId")
                        .HasColumnType("text")
                        .HasColumnName("stripe_product_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_plans");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_plans_name");

                    b.ToTable("plans", (string)null);
                });

            modelBuilder.Entity("Billing.Domain.Aggregates.PlanAssignment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<string>("AssignedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("assigned_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plan_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_kind");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_plan_assignments");

                    b.HasIndex("PlanId", "VersionNumber")
                        .HasDatabaseName("ix_plan_assignments_plan_id_version_number");

                    b.HasIndex("SubjectKind", "SubjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_plan_assignments_subject_kind_subject_id");

                    b.ToTable("plan_assignments", (string)null);
                });

            modelBuilder.Entity("Billing.Domain.Aggregates.PlanAuditEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor");

                    b.Property<int?>("AffectedSubjects")
                        .HasColumnType("integer")
                        .HasColumnName("affected_subjects");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plan_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("Subject")
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_plan_audit_entries");

                    b.HasIndex("PlanId", "OccurredAt")
                        .HasDatabaseName("ix_plan_audit_entries_plan_id_occurred_at");

                    b.ToTable("plan_audit_entries", (string)null);
                });

            modelBuilder.Entity("Billing.Domain.Aggregates.PlanVersion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ArchiveReason")
                        .HasColumnType("text")
                        .HasColumnName("archive_reason");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("ArchivedBy")
                        .HasColumnType("text")
                        .HasColumnName("archived_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Currency")
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plan_id");

                    b.Property<long?>("PriceMinorUnits")
                        .HasColumnType("bigint")
                        .HasColumnName("price_minor_units");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("StripePriceId")
                        .HasColumnType("text")
                        .HasColumnName("stripe_price_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValuesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("values_json");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_plan_versions");

                    b.HasIndex("PlanId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_plan_versions_plan_id_version_number");

                    b.ToTable("plan_versions", (string)null);
                });

            modelBuilder.Entity("Billing.Domain.Aggregates.ProcessedStripeEvent", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("text")
                        .HasColumnName("event_id");

                    b.Property<string>("Outcome")
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("EventId")
                        .HasName("pk_processed_stripe_events");

                    b.ToTable("processed_stripe_events", (string)null);
                });

            modelBuilder.Entity("Billing.Domain.Aggregates.PromotionCampaign", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AlertThresholdPercent")
                        .HasColumnType("integer")
                        .HasColumnName("alert_threshold_percent");

                    b.Property<DateTimeOffset?>("AlertedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alerted_at");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<long>("IssuedRedemptions")
                        .HasColumnType("bigint")
                        .HasColumnName("issued_redemptions");

                    b.Property<int>("MaxPerSubject")
                        .HasColumnType("integer")
                        .HasColumnName("max_per_subject");

                    b.Property<int>("MinimumAccountAgeDays")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_account_age_days");

                    b.Property<DateTimeOffset?>("PausedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paused_at");

                    b.Property<string>("PausedBy")
                        .HasColumnType("text")
                        .HasColumnName("paused_by");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plan");

                    b.Property<int>("RequiredSignals")
                        .HasColumnType("integer")
                        .HasColumnName("required_signals");

                    b.Property<DateTimeOffset?>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("SubjectKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_kind");

                    b.Property<long>("TotalBudgetRedemptions")
                        .HasColumnType("bigint")
                        .HasColumnName("total_budget_redemptions");

                    b.Property<int>("TrialDays")
                        .HasColumnType("integer")
                        .HasColumnName("trial_days");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_promotion_campaigns");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_promotion_campaigns_code");

                    b.ToTable("promotion_campaigns", null, t =>
                        {
                            t.HasCheckConstraint("ck_promotion_campaigns_within_budget", "total_budget_redemptions > 0 AND issued_redemptions >= 0 AND issued_redemptions <= total_budget_redemptions");
                        });
                });

            modelBuilder.Entity("Billing.Domain.Aggregates.PromotionIdentityMark", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CampaignId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("RedemptionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("redemption_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_promotion_identity_marks");

                    b.HasIndex("RedemptionId")
                        .HasDatabaseName("ix_promotion_identity_marks_redemption_id");

                    b.HasIndex("CampaignId", "Kind", "Hash")
                        .IsUnique()
                        .HasDatabaseName("ix_promotion_identity_marks_campaign_id_kind_hash");

                    b.ToTable("promotion_identity_marks", (string)null);
                });

            modelBuilder.Entity("Billing.Domain.Aggregates.PromotionRedemption", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CampaignId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<DateTimeOffset?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTimeOffset>("RedeemedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redeemed_at");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.Property<string>("StripeSubscriptionId")
                        .HasColumnType("text")
                        .HasColumnName("stripe_subscription_id");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_kind");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_promotion_redemptions");

                    b.HasIndex("EndsAt")
                        .HasDatabaseName("ix_promotion_redemptions_ends_at")
                        .HasFilter("ends_at IS NOT NULL AND expired_at IS NULL");

                    b.HasIndex("OwnerUserId", "RedeemedAt")
                        .HasDatabaseName("ix_promotion_redemptions_owner_user_id_redeemed_at");

                    b.HasIndex("CampaignId", "SubjectKind", "SubjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_promotion_redemptions_campaign_id_subject_kind_subject_id");

                    b.ToTable("promotion_redemptions", (string)null);
                });

            modelBuilder.Entity("Billing.Domain.Aggregates.StripeCustomer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("StripeCustomerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stripe_customer_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_stripe_customers");

                    b.HasIndex("StripeCustomerId")
                        .IsUnique()
                        .HasDatabaseName("ix_stripe_customers_stripe_customer_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_stripe_customers_user_id");

                    b.ToTable("stripe_customers", (string)null);
                });

            modelBuilder.Entity("Billing.Domain.Aggregates.Subscription", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<bool>("CancelAtPeriodEnd")
                        .HasColumnType("boolean")
                        .HasColumnName("cancel_at_period_end");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_end");

                    b.Property<DateTimeOffset?>("GracePeriodEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("grace_period_ends_at");

                    b.Property<DateTimeOffset?>("LastEventAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_event_at");

                    b.Property<string>("LatestInvoiceId")
                        .HasColumnType("text")
                        .HasColumnName("latest_invoice_id");

                    b.Property<string>("PayerUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payer_user_id");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plan_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StripeSubscriptionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stripe_subscription_id");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_kind");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("UseCreditBeforeCharging")
                        .HasColumnType("boolean")
                        .HasColumnName("use_credit_before_charging");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_subscriptions_plan_id");

                    b.HasIndex("StripeSubscriptionId")
                        .IsUnique()
                        .HasDatabaseName("ix_subscriptions_stripe_subscription_id");

                    b.HasIndex("SubjectKind", "SubjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_subscriptions_subject_kind_subject_id")
                        .HasFilter("status IN ('Trialing', 'Active', 'PastDue')");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("Billing.Domain.Aggregates.PlanAssignment", b =>
                {
                    b.HasOne("Billing.Domain.Aggregates.Plan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plan_assignments_plans_plan_id");
                });

            modelBuilder.Entity("Billing.Domain.Aggregates.PlanAuditEntry", b =>
                {
                    b.HasOne("Billing.Domain.Aggregates.Plan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plan_audit_entries_plans_plan_id");
                });

            modelBuilder.Entity("Billing.Domain.Aggregates.PlanVersion", b =>
                {
                    b.HasOne("Billing.Domain.Aggregates.Plan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_plan_versions_plans_plan_id");
                });

            modelBuilder.Entity("Billing.Domain.Aggregates.PromotionIdentityMark", b =>
                {
                    b.HasOne("Billing.Domain.Aggregates.PromotionRedemption", null)
                        .WithMany()
                        .HasForeignKey("RedemptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_promotion_identity_marks_promotion_redemptions_redemption_id");
                });

            modelBuilder.Entity("Billing.Domain.Aggregates.PromotionRedemption", b =>
                {
                    b.HasOne("Billing.Domain.Aggregates.PromotionCampaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_promotion_redemptions_promotion_campaigns_campaign_id");
                });

            modelBuilder.Entity("Billing.Domain.Aggregates.Subscription", b =>
                {
                    b.HasOne("Billing.Domain.Aggregates.Plan", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_plans_plan_id");
                });
#pragma warning restore 612, 618
        }
    }
}
