<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <RootNamespace>Isle.Api</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />

        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5"/>
        <PackageReference Include="Microsoft.AspNetCore.SignalR.StackExchangeRedis" Version="10.0.10" />
        <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.10" />
        <PackageReference Include="TheIsleEvrimaRconClient" Version="2.1.0" />
        <PackageReference Include="WolverineFx" Version="6.21.0" />
        <PackageReference Include="WolverineFx.EntityFrameworkCore" Version="6.21.0" />
        <PackageReference Include="WolverineFx.Http" Version="6.21.0" />
        <PackageReference Include="WolverineFx.Postgresql" Version="6.21.0" />
        <PackageReference Include="WolverineFx.RabbitMQ" Version="6.21.0" />

        <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="10.0.9" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers" Version="10.0.9" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.9">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\AppEnvironment\AppEnvironment.csproj" />
      <ProjectReference Include="..\Echo.Realtime\Echo.Realtime.csproj" />
      <ProjectReference Include="..\Identity.Contracts\Identity.Contracts.csproj" />
      <ProjectReference Include="..\Isle.Contracts\Isle.Contracts.csproj" />
      <ProjectReference Include="..\Isle.Domain\Isle.Domain.csproj" />
      <ProjectReference Include="..\Isle.Infrastructure\Isle.Infrastructure.csproj" />
      <ProjectReference Include="..\IsleBridge.Sdk\IsleBridge.Sdk\IsleBridge.Sdk.csproj" />
      <ProjectReference Include="..\Messaging\Messaging.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Handlers\Events\Voice\" />
      <Folder Include="Voice\" />
    </ItemGroup>

</Project>
