#!/usr/bin/env bash

set -e

# Terminal Styling
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
BOLD='\033[1m'
NC='\033[0m'

echo -e "${CYAN}${BOLD}"
echo "===================================================="
echo "          Venta Stack Self-Hosted Installer          "
echo "===================================================="
echo -e "${NC}"

generate_password() {
    openssl rand -hex 16 2>/dev/null || echo "SecurePass_$(date +%s)_${RANDOM}"
}

# ---------------------------------------------------------------------
# 1. Core General Settings
# ---------------------------------------------------------------------
echo -e "${BOLD}--- General Settings ---${NC}"
read -p "Enter Instance Name (Default: Venta Selfhosted Template): " INSTANCE_NAME
INSTANCE_NAME=${INSTANCE_NAME:-Venta Selfhosted Template}

read -p "Enter your public domain/IP (Default: localhost): " INSTANCE_DOMAIN
INSTANCE_DOMAIN=${INSTANCE_DOMAIN:-localhost}

if [ "$INSTANCE_DOMAIN" = "localhost" ]; then
    DEFAULT_PUBLIC_URL="http://localhost:8080"
    DEFAULT_STORAGE_PUBLIC_URL="http://localhost:9000"
else
    DEFAULT_PUBLIC_URL="https://${INSTANCE_DOMAIN}"
    DEFAULT_STORAGE_PUBLIC_URL="https://storage.${INSTANCE_DOMAIN}"
fi

read -p "Enter application External URL (Default: $DEFAULT_PUBLIC_URL): " PUBLIC_URL
PUBLIC_URL=${PUBLIC_URL:-$DEFAULT_PUBLIC_URL}

read -p "Enter Storage External URL (Default: $DEFAULT_STORAGE_PUBLIC_URL): " STORAGE_PUBLIC_URL
STORAGE_PUBLIC_URL=${STORAGE_PUBLIC_URL:-$DEFAULT_STORAGE_PUBLIC_URL}

DEFAULT_DATA_DIR="/var/lib/venta-stack"
read -p "Enter local directory for persistent data (Default: $DEFAULT_DATA_DIR): " DATA_DIR
DATA_DIR=${DATA_DIR:-$DEFAULT_DATA_DIR}

# ---------------------------------------------------------------------
# 2. Database Selection (Internal vs External)
# ---------------------------------------------------------------------
echo -e "\n${BOLD}--- Database Configuration ---${NC}"
echo "Would you like to use the built-in PostgreSQL container or connect to an existing external database?"
echo "  1) Use built-in PostgreSQL container (Default)"
echo "  2) Connect to an external PostgreSQL database"
read -p "Selection [1-2]: " DB_CHOICE
DB_CHOICE=${DB_CHOICE:-1}

if [ "$DB_CHOICE" = "2" ]; then
    USE_LOCAL_POSTGRES="false"
    echo -e "\n${YELLOW}Please enter your external database credentials:${NC}"
    read -p "PostgreSQL Hostname: " DB_HOST
    read -p "PostgreSQL Port (Default: 5432): " DB_PORT
    DB_PORT=${DB_PORT:-5432}
    read -p "PostgreSQL Username (Default: postgres): " DB_USER
    DB_USER=${DB_USER:-postgres}
    read -s -p "PostgreSQL Password: " DB_PASS
    echo "" # New line after hidden password input
else
    USE_LOCAL_POSTGRES="true"
    DB_HOST="postgres"
    DB_PORT="5432"
    DB_USER="postgres"
    DB_PASS=$(generate_password)
fi

# ---------------------------------------------------------------------
# 3. Rest of Infrastructure Infrastructure Keys
# ---------------------------------------------------------------------
REDIS_PASSWORD=$(generate_password)
RABBITMQ_PASSWORD=$(generate_password)
SCYLLA_PASSWORD=$(generate_password)
MINIO_ROOT_PASSWORD=$(generate_password)
IDENTITY_KEY_PASSWORD=$(openssl rand -hex 32 2>/dev/null || generate_password)
MINIO_ROOT_USER="venta_access_$(openssl rand -hex 4)"

if command -v openssl &> /dev/null; then
    FED_PRIV_RAW=$(openssl rand 32)
    FED_PUB_RAW=$(openssl rand 32)
    FED_PRIV_B64=$(echo -n "$FED_PRIV_RAW" | base64 | tr -d '\n\r')
    FED_PUB_B64=$(echo -n "$FED_PUB_RAW" | base64 | tr -d '\n\r')
else
    FED_PRIV_B64="U29tZUZhbGxiYWNrUHJpdmF0ZUtleVdoYXRldmVyMTIzNDU="
    FED_PUB_B64="U29tZUZhbGxiYWNrUHVibGljS2V5V2hhdGV2ZXIxMjM0NTY="
fi

# ---------------------------------------------------------------------
# 4. Environment (.env) Writing
# ---------------------------------------------------------------------
cat << EOF > .env
# Generated by Venta Installer on $(date)
DATA_DIR=$DATA_DIR
INSTANCE_NAME=$INSTANCE_NAME
INSTANCE_DOMAIN=$INSTANCE_DOMAIN
INSTANCE_URL=$PUBLIC_URL
PUBLIC_URL=$PUBLIC_URL
STORAGE_PUBLIC_URL=$STORAGE_PUBLIC_URL

# Profiles control whether docker spins up internal engines
USE_LOCAL_POSTGRES=$USE_LOCAL_POSTGRES

# Database Routing Configuration
DATABASE_HOSTNAME=$DB_HOST
DATABASE_PORT=$DB_PORT
DATABASE_USERNAME=$DB_USER
DATABASE_PASSWORD=$DB_PASS

# Rest of Stack Infrastructure
REDIS_PASSWORD=$REDIS_PASSWORD
RABBITMQ_PASSWORD=$RABBITMQ_PASSWORD
SCYLLA_PASSWORD=$SCYLLA_PASSWORD
MINIO_ROOT_USER=$MINIO_ROOT_USER
MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD
IDENTITY_KEY_PASSWORD=$IDENTITY_KEY_PASSWORD

# Crypto Federation
FEDERATION_PRIVATE_KEY_BASE_64=$FED_PRIV_B64
FEDERATION_PUBLIC_KEY_BASE_64=$FED_PUB_B64
EOF

# ---------------------------------------------------------------------
# 5. Directory Preparation
# ---------------------------------------------------------------------
echo -e "\n${BOLD}--- Preparing Host Directories ---${NC}"
MKDIR_CMD="mkdir -p"
if [ ! -w "$(dirname "$DATA_DIR")" ] && [ ! -d "$DATA_DIR" ]; then
    MKDIR_CMD="sudo mkdir -p"
fi

# Skip making postgres host directories if we aren't spinning up an internal database
if [ "$USE_LOCAL_POSTGRES" = "true" ]; then
    $MKDIR_CMD "$DATA_DIR/postgres"
fi
$MKDIR_CMD "$DATA_DIR/redis" "$DATA_DIR/rabbitmq" "$DATA_DIR/scylla" "$DATA_DIR/minio"

if [ "$MKDIR_CMD" = "sudo mkdir -p" ]; then
    sudo chmod -R 777 "$DATA_DIR"
else
    chmod -R 777 "$DATA_DIR"
fi

# ---------------------------------------------------------------------
# 6. Production Nginx Reverse Proxy Config
# ---------------------------------------------------------------------
cat << 'EOF' > nginx.conf
server {
    listen 80;
    server_name INSTANCE_DOMAIN_PLACEHOLDER;
    client_max_body_size 100M;

    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    server_name storage.INSTANCE_DOMAIN_PLACEHOLDER;
    client_max_body_size 500M;

    location / {
        proxy_pass http://127.0.0.1:9000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
EOF
sed -i "s/INSTANCE_DOMAIN_PLACEHOLDER/$INSTANCE_DOMAIN/g" nginx.conf

echo -e "\n----------------------------------------------------"
read -p "Setup complete. Boot stack containers via docker-compose now? (y/N): " choice
case "$choice" in 
  y|Y ) 
    docker compose up -d || docker-compose up -d
    ;;
  * ) 
    echo -e "${YELLOW}Exiting setup script. Run 'docker compose up -d' manually to boot your instance.${NC}"
    ;;
esac