using System.Security.Claims;
using Facet.Extensions;
using Identity.Application.Dtos.Request;
using Identity.Application.Dtos.Response;
using Domain;
using Identity.Contracts.Bus.Events;
using Identity.Domain.Entities;
using Identity.Infrastructure.Persistence;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Wolverine;
using Wolverine.Http;

namespace Identity.Application.Endpoints;

public class MlsDeviceEndpoint
{
    /// <summary>Ceiling on a single upload.</summary>
    public const int MaxKeyPackagesPerUpload = 200;

    /// <summary>Registers a device, or re-registers one that already exists.</summary>
    [Authorize]
    [WolverinePost("api/v1/devices")]
    public async Task<(IResult, DeviceRegistered?)> CreateDevice(CreateMLSDeviceDto dto,[NotBody] IMessageBus messageBus, [NotBody] ClaimsPrincipal user, [NotBody] MicroserviceContext ctx )
    {
        var userId = user.FindFirstValue(ClaimTypes.NameIdentifier);
        if(string.IsNullOrWhiteSpace(userId)) return (Results.Unauthorized(), null);

        var now = DateTimeOffset.UtcNow;

        // Structure and expiry only - the server does not hold the account identity private half
        // and therefore cannot check the signature.
        var certificateError = DeviceCertificate.Validate(
            dto.DeviceCertificate, dto.CertificateIssuedAt, dto.CertificateExpiresAt, now);
        if (certificateError is not null) return (Results.BadRequest(certificateError), null);

        var existingDevice = await ctx.UserDevices.FirstOrDefaultAsync(x => x.ClientDeviceId == dto.ClientDeviceId && x.UserId == userId);

        // A collision with another user's device used to delete that user's row (and cascade away
        // their key packages and backup) purely because ClientDeviceId is client-supplied and was
        // globally unique - any account could destroy another's device registration by claiming its
        // id. The id is scoped per user now, so a collision across users simply isn't one.

        if (existingDevice is not null)
        {
            var incomingKey = dto.IdentityPublicKey ?? [];
            var rotated = incomingKey.Length > 0
                          && !incomingKey.AsSpan().SequenceEqual(existingDevice.IdentityPublicKey);

            if (rotated)
            {
                existingDevice.IdentityPublicKey = incomingKey;
                existingDevice.UpdatedAt = DateTimeOffset.UtcNow;

                // Every package on file was generated by the identity that just went away.
                await PurgeKeyPackagesAsync(ctx, existingDevice.Id);
            }

            // The name and type are cheap to keep current; a renamed handset should not need a
            // second endpoint to say so.
            if (!string.IsNullOrWhiteSpace(dto.DeviceName)) existingDevice.DeviceName = dto.DeviceName;

            ApplyCertificate(existingDevice, dto);
            ApplyCapabilities(existingDevice, dto);

            return (
                Results.Ok(ToRegistrationDto(existingDevice, rotated)),
                rotated
                    ? new DeviceRegistered
                    {
                        DeviceId = existingDevice.Id,
                        ClientDeviceId = existingDevice.ClientDeviceId,
                        DeviceName = existingDevice.DeviceName,
                        UserId = existingDevice.UserId,
                        IdentityRotated = true,
                    }
                    : null);
        }

        var device = UserDevice.Create(new CreateUserDeviceParams()
        {
            UserId = userId,
            ClientDeviceId = dto.ClientDeviceId,
            DeviceName = dto.DeviceName,
            DeviceType = dto.DeviceType,
            IdentityPublicKey = dto.IdentityPublicKey,
        });
        ApplyCertificate(device, dto);
        ApplyCapabilities(device, dto);
        ctx.UserDevices.Add(device);

        return (Results.Ok(ToRegistrationDto(device, identityRotated: false)), new DeviceRegistered()
        {
            DeviceId = device.Id,
            ClientDeviceId = device.ClientDeviceId,
            DeviceName = device.DeviceName,
            UserId = device.UserId,
        });
    }

    /// <summary>Throws away every key package this device has on file.</summary>
    [Authorize]
    [WolverineDelete("api/v1/devices/client/{deviceId}/key-packages")]
    public static async Task<IResult> ResetKeyPackages(string deviceId,
        [NotBody] ClaimsPrincipal user, [NotBody] MicroserviceContext ctx)
    {
        var userId = user.FindFirstValue(ClaimTypes.NameIdentifier);
        if (string.IsNullOrWhiteSpace(userId)) return Results.Unauthorized();

        var device = await ctx.UserDevices.AsNoTracking()
            .FirstOrDefaultAsync(d => d.ClientDeviceId == deviceId && d.UserId == userId);

        if (device is null)
        {
            // ClientDeviceId is only unique per user, so "exists but is not yours" is a real and
            // distinguishable case.
            var claimedByAnotherUser = await ctx.UserDevices.AnyAsync(d => d.ClientDeviceId == deviceId);
            return claimedByAnotherUser ? Results.Forbid() : Results.NotFound();
        }

        var deleted = await PurgeKeyPackagesAsync(ctx, device.Id);

        return Results.Ok(new ResetKeyPackagesResultDto { DeletedCount = deleted });
    }

    /// <summary>Reissues a device's certificate without re-registering it.</summary>
    [Authorize]
    [WolverinePut("api/v1/devices/client/{deviceId}/certificate")]
    public static async Task<IResult> UpdateCertificate(string deviceId, UpdateDeviceCertificateDto dto,
        [NotBody] ClaimsPrincipal user, [NotBody] MicroserviceContext ctx)
    {
        var userId = user.FindFirstValue(ClaimTypes.NameIdentifier);
        if (string.IsNullOrWhiteSpace(userId)) return Results.Unauthorized();

        var now = DateTimeOffset.UtcNow;
        if (dto.Certificate is null or { Length: 0 }) return Results.BadRequest("certificate is required");

        var error = DeviceCertificate.Validate(dto.Certificate, dto.IssuedAt, dto.ExpiresAt, now);
        if (error is not null) return Results.BadRequest(error);

        var device = await ctx.UserDevices
            .FirstOrDefaultAsync(d => d.ClientDeviceId == deviceId && d.UserId == userId);
        if (device is null) return Results.NotFound();

        device.Certificate = dto.Certificate;
        device.CertificateIssuedAt = dto.IssuedAt;
        device.CertificateExpiresAt = dto.ExpiresAt;
        device.CertificateIdentityKeyVersion = dto.IdentityKeyVersion;
        device.UpdatedAt = now;

        return Results.Ok(new { deviceId, expiresAt = dto.ExpiresAt });
    }

    private static void ApplyCertificate(UserDevice device, CreateMLSDeviceDto dto)
    {
        if (dto.DeviceCertificate is null or { Length: 0 }) return;

        device.Certificate = dto.DeviceCertificate;
        device.CertificateIssuedAt = dto.CertificateIssuedAt;
        device.CertificateExpiresAt = dto.CertificateExpiresAt;
        device.CertificateIdentityKeyVersion = dto.CertificateIdentityKeyVersion;
    }

    /// <summary>Records what this build of the client can actually do.</summary>
    private static void ApplyCapabilities(UserDevice device, CreateMLSDeviceDto dto)
    {
        if (dto.Capabilities is null) return;

        device.Capabilities = dto.Capabilities
            .Where(c => !string.IsNullOrWhiteSpace(c))
            .Select(c => c.Trim())
            .Distinct()
            .OrderBy(c => c)
            .ToList();
    }

    /// <summary>Removes every key package row for a device row id and reports how many went.
    /// Deliberately unfiltered - a consumed or expired package is no more usable than a live one
    /// whose private half has been destroyed.</summary>
    private static async Task<int> PurgeKeyPackagesAsync(MicroserviceContext ctx, string deviceRowId)
    {
        var packages = await ctx.UserKeyPackages.Where(p => p.DeviceId == deviceRowId).ToListAsync();
        if (packages.Count == 0) return 0;

        ctx.UserKeyPackages.RemoveRange(packages);
        return packages.Count;
    }

    /// <summary>The device as the client already reads it, plus the one bit it cannot infer: whether
    /// this call rotated the identity key and therefore emptied the key-package stock.</summary>
    private static DeviceRegistrationDto ToRegistrationDto(UserDevice device, bool identityRotated) =>
        new()
        {
            Id = device.Id,
            ClientDeviceId = device.ClientDeviceId,
            DeviceName = device.DeviceName,
            DeviceType = device.DeviceType,
            IdentityPublicKey = device.IdentityPublicKey,
            Status = device.Status,
            LastSeen = device.LastSeen,
            UserId = device.UserId,
            CreatedAt = device.CreatedAt,
            UpdatedAt = device.UpdatedAt,
            IdentityRotated = identityRotated,
        };

    // GET api/v1/devices lives on MlsDeviceController.

    [Authorize]
    [WolverinePost("api/v1/devices/client/{deviceId}/key-packages")]
    public async Task<IResult> AddKeyPackagesForDeviceAsync(string deviceId, [FromBody] AddMLSDeviceKeyPackagesDto dto, [NotBody] ClaimsPrincipal user, [NotBody] MicroserviceContext ctx)
    {
        var userId = user.FindFirstValue(ClaimTypes.NameIdentifier);
        if(string.IsNullOrWhiteSpace(userId)) return Results.Unauthorized();

        var device = await ctx.UserDevices.AsNoTracking()
            .FirstOrDefaultAsync(x => x.ClientDeviceId == deviceId && x.UserId == userId);
        if(device is null) return Results.NotFound();

        var incoming = dto.KeyPackages ?? [];

        // A last-resort package is reusable, so every group that joins through one shares init key
        // material and the joining leaf has no forward secrecy from that point back.
        if (incoming.Any(p => p.IsLastResort))
        {
            var protectionLevel = await ctx.Users
                .Where(u => u.Id == userId)
                .Select(u => u.ProtectionLevel)
                .FirstOrDefaultAsync();

            if (protectionLevel == ProtectionLevel.VerifiedDevices)
                return Results.BadRequest(
                    "This account is on VerifiedDevices, which does not permit the reusable " +
                    "last-resort key package. Upload single-use packages only.");
        }

        // An empty upload is a success, not a client error.
        if (incoming.Count == 0) return Results.Ok(new AddKeyPackagesResultDto { Added = 0 });

        if (incoming.Count > MaxKeyPackagesPerUpload)
            return Results.BadRequest($"At most {MaxKeyPackagesPerUpload} key packages per upload");

        List<UserKeyPackage> packages;
        try
        {
            packages = incoming.Select(p => UserKeyPackage.Create(new CreateUserKeyPackageParams()
            {
                UserId = userId,
                DeviceId = device.Id,
                KeyPackage = p.KeyPackage,
                ExpiresAt = p.ExpiresAt,
                IsLastResort = p.IsLastResort,
            })).ToList();
        }
        catch (ArgumentException ex)
        {
            // GetCipherSuite rejects anything that is not a well-formed KeyPackage header.
            return Results.BadRequest(ex.Message);
        }

        // A device keeps exactly one last-resort package; a new one supersedes the old rather than
        // accumulating, which keeps the reuse window bounded to the newest key.
        if (packages.Any(p => p.IsLastResort))
        {
            var superseded = await ctx.UserKeyPackages
                .Where(p => p.DeviceId == device.Id && p.IsLastResort)
                .ToListAsync();
            ctx.UserKeyPackages.RemoveRange(superseded);
        }

        ctx.UserKeyPackages.AddRange(packages);

        return Results.Ok(new AddKeyPackagesResultDto { Added = packages.Count });
    }

    /// <summary>
    /// Unregisters one of the caller's own devices: the row goes, and with it (by cascade) its key
    /// packages, its encrypted backup and its push tokens - so a handset that has been wiped, sold
    /// or signed out stops being handed key packages for new groups and stops being rung.
    /// </summary>
    [Authorize]
    [WolverineDelete("api/v1/devices/client/{deviceId}")]
    public static async Task<(IResult, DeviceRemoved?)> RemoveDevice(string deviceId,
        [NotBody] ClaimsPrincipal user, [NotBody] MicroserviceContext ctx)
    {
        var userId = user.FindFirstValue(ClaimTypes.NameIdentifier);
        if (string.IsNullOrWhiteSpace(userId)) return (Results.Unauthorized(), null);

        var device = await ctx.UserDevices
            .FirstOrDefaultAsync(d => d.ClientDeviceId == deviceId && d.UserId == userId);
        if (device is null) return (Results.NotFound(), null);

        var sessions = await ctx.LoginSessions
            .Where(s => s.DeviceId == device.Id && s.RevokedAt == null)
            .ToListAsync();
        foreach (var session in sessions)
        {
            session.Revoke();
        }

        ctx.UserDevices.Remove(device);

        return (Results.NoContent(), new DeviceRemoved
        {
            UserId = userId,
            DeviceId = device.Id,
            ClientDeviceId = device.ClientDeviceId,
        });
    }

    // GET api/v1/devices/{deviceId}/key-packages is gone.
}
