// <auto-generated />
using System;
using System.Collections.Generic;
using Isle.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Isle.Infrastructure.Migrations
{
    [DbContext(typeof(MicroserviceContext))]
    partial class MicroserviceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "hstore");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Isle.Domain.Aggregates.Player", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<string>("SteamId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("steam_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<long>("Xp")
                        .HasColumnType("bigint")
                        .HasColumnName("xp");

                    b.HasKey("Id")
                        .HasName("pk_players");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("Isle.Domain.Aggregates.Storage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("MaxSlotCount")
                        .HasColumnType("integer")
                        .HasColumnName("max_slot_count");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("player_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_storages");

                    b.HasIndex("PlayerId")
                        .IsUnique()
                        .HasDatabaseName("ix_storages_player_id");

                    b.ToTable("storages", (string)null);
                });

            modelBuilder.Entity("Isle.Domain.Entity.StorageSlot", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("species");

                    b.Property<string>("StorageId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_storage_slots");

                    b.HasIndex("StorageId")
                        .HasDatabaseName("ix_storage_slots_storage_id");

                    b.ToTable("storage_slots", (string)null);
                });

            modelBuilder.Entity("Isle.Domain.Aggregates.Storage", b =>
                {
                    b.HasOne("Isle.Domain.Aggregates.Player", "Player")
                        .WithOne("Storage")
                        .HasForeignKey("Isle.Domain.Aggregates.Storage", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_storages_players_player_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Isle.Domain.Entity.StorageSlot", b =>
                {
                    b.HasOne("Isle.Domain.Aggregates.Storage", "Storage")
                        .WithMany("Slots")
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_storage_slots_storages_storage_id");

                    b.OwnsOne("Isle.Domain.Entity.DinoHealthData", "HealthData", b1 =>
                        {
                            b1.Property<string>("StorageSlotId")
                                .HasColumnType("text")
                                .HasColumnName("id");

                            b1.Property<long>("Health")
                                .HasColumnType("bigint")
                                .HasColumnName("health_data_health");

                            b1.Property<long>("Hunger")
                                .HasColumnType("bigint")
                                .HasColumnName("health_data_hunger");

                            b1.Property<long>("Stamina")
                                .HasColumnType("bigint")
                                .HasColumnName("health_data_stamina");

                            b1.Property<long>("Thirst")
                                .HasColumnType("bigint")
                                .HasColumnName("health_data_thirst");

                            b1.HasKey("StorageSlotId");

                            b1.ToTable("storage_slots");

                            b1.WithOwner()
                                .HasForeignKey("StorageSlotId")
                                .HasConstraintName("fk_storage_slots_storage_slots_id");
                        });

                    b.OwnsOne("IsleBridge.Sdk.Models.MutationsData", "Mutations", b1 =>
                        {
                            b1.Property<string>("StorageSlotId")
                                .HasColumnType("text")
                                .HasColumnName("id");

                            b1.Property<int>("ElderStacks")
                                .HasColumnType("integer")
                                .HasColumnName("mutations_elder_stacks");

                            b1.Property<Dictionary<string, string>>("Slots")
                                .HasColumnType("hstore")
                                .HasColumnName("mutations_slots");

                            b1.PrimitiveCollection<List<string>>("Unlocks")
                                .HasColumnType("text[]")
                                .HasColumnName("mutations_unlocks");

                            b1.HasKey("StorageSlotId");

                            b1.ToTable("storage_slots");

                            b1.WithOwner()
                                .HasForeignKey("StorageSlotId")
                                .HasConstraintName("fk_storage_slots_storage_slots_id");
                        });

                    b.Navigation("HealthData")
                        .IsRequired();

                    b.Navigation("Mutations")
                        .IsRequired();

                    b.Navigation("Storage");
                });

            modelBuilder.Entity("Isle.Domain.Aggregates.Player", b =>
                {
                    b.Navigation("Storage")
                        .IsRequired();
                });

            modelBuilder.Entity("Isle.Domain.Aggregates.Storage", b =>
                {
                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
