// <auto-generated />
using System;
using System.Collections.Generic;
using Identity.Domain.Enums;
using Identity.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Identity.Infrastructure.Migrations
{
    [DbContext(typeof(MicroserviceContext))]
    [Migration("20260801213153_AddDeviceCertificateRevocation")]
    partial class AddDeviceCertificateRevocation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "age_vertification_level", new[] { "ai_estimation", "goverment_id", "none", "self_declaration" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "device_status", new[] { "active", "removed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "device_type", new[] { "desktop", "mobile", "web" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "direct_message_settings", new[] { "allow_all", "filter_all", "filter_non_friends" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "privacy_settings", new[] { "allow_data_collection", "allow_data_use_for_personalization", "allow_voice_recorded_in_clips", "none" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "push_token_kind", new[] { "apns_voip", "fcm" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "theme", new[] { "dark", "light", "midnight", "system" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_status", new[] { "active", "banned", "deleted", "inactive", "pending_deletion", "purge_in_progress" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_type", new[] { "admin", "bot", "default", "moderator" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Identity.Domain.Aggregates.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<byte[]>("AccountIdentityKeyRotationSignature")
                        .HasColumnType("bytea")
                        .HasColumnName("account_identity_key_rotation_signature");

                    b.Property<DateTimeOffset?>("AccountIdentityKeyUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("account_identity_key_updated_at");

                    b.Property<int>("AccountIdentityKeyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("account_identity_key_version");

                    b.Property<byte[]>("AccountIdentityPublicKey")
                        .HasColumnType("bytea")
                        .HasColumnName("account_identity_public_key");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletionRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_requested_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<string>("FederatedServerId")
                        .HasColumnType("text")
                        .HasColumnName("federated_server_id");

                    b.Property<string>("JsonSettings")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("json_settings");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<DateTimeOffset?>("MasterKeyPasswordWrappingInvalidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("master_key_password_wrapping_invalidated_at");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<DateTimeOffset?>("PhoneVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("phone_verified_at");

                    b.Property<int>("ProtectionLevel")
                        .HasColumnType("integer")
                        .HasColumnName("protection_level");

                    b.Property<byte[]>("ProtectionLevelAssertion")
                        .HasColumnType("bytea")
                        .HasColumnName("protection_level_assertion");

                    b.Property<DateTimeOffset?>("ProtectionLevelUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("protection_level_updated_at");

                    b.Property<int>("ProtectionLevelVersion")
                        .HasColumnType("integer")
                        .HasColumnName("protection_level_version");

                    b.Property<DateTimeOffset?>("PurgeScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purge_scheduled_at");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<UserStatus>("Status")
                        .HasColumnType("user_status")
                        .HasColumnName("status");

                    b.Property<string>("SteamId")
                        .HasColumnType("text")
                        .HasColumnName("steam_id");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.Property<string>("UserPreferencesId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_preferences_id");

                    b.Property<UserType>("UserType")
                        .HasColumnType("user_type")
                        .HasColumnName("user_type");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_asp_net_users_email");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_asp_net_users_phone_number");

                    b.HasIndex("UserPreferencesId")
                        .IsUnique()
                        .HasDatabaseName("ix_asp_net_users_user_preferences_id");

                    b.ToTable("asp_net_users", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.Entities.IdentityAuditEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("ClientDeviceId")
                        .HasColumnType("text")
                        .HasColumnName("client_device_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Detail")
                        .HasColumnType("text")
                        .HasColumnName("detail");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_identity_audit_events");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_identity_audit_events_user_id_created_at");

                    b.ToTable("identity_audit_events", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.Entities.LoginSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_name");

                    b.Property<DeviceType>("DeviceType")
                        .HasColumnType("device_type")
                        .HasColumnName("device_type");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_login_sessions");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_login_sessions_device_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_login_sessions_user_id");

                    b.ToTable("login_sessions", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.Entities.RevokedDeviceCertificate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CertificateExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("certificate_expires_at");

                    b.Property<string>("CertificateFingerprint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("certificate_fingerprint");

                    b.Property<string>("ClientDeviceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_device_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("IdentityKeyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("identity_key_version");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_revoked_device_certificates");

                    b.HasIndex("UserId", "CertificateFingerprint")
                        .IsUnique()
                        .HasDatabaseName("ix_revoked_device_certificates_user_id_certificate_fingerprint");

                    b.HasIndex("UserId", "RevokedAt")
                        .HasDatabaseName("ix_revoked_device_certificates_user_id_revoked_at");

                    b.ToTable("revoked_device_certificates", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.Entities.UserBackupTransfer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<byte[]>("CipherText")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("cipher_text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("SourceDeviceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_device_id");

                    b.Property<string>("TargetDeviceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_device_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<byte[]>("WrappedTo")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("wrapped_to");

                    b.HasKey("Id")
                        .HasName("pk_user_backup_transfers");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_user_backup_transfers_expires_at");

                    b.HasIndex("UserId", "TargetDeviceId")
                        .HasDatabaseName("ix_user_backup_transfers_user_id_target_device_id");

                    b.ToTable("user_backup_transfers", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.Entities.UserDevice", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.PrimitiveCollection<List<string>>("Capabilities")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("capabilities");

                    b.Property<byte[]>("Certificate")
                        .HasColumnType("bytea")
                        .HasColumnName("certificate");

                    b.Property<DateTimeOffset?>("CertificateExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("certificate_expires_at");

                    b.Property<int>("CertificateIdentityKeyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("certificate_identity_key_version");

                    b.Property<DateTimeOffset?>("CertificateIssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("certificate_issued_at");

                    b.Property<string>("ClientDeviceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_device_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_name");

                    b.Property<DeviceType>("DeviceType")
                        .HasColumnType("device_type")
                        .HasColumnName("device_type");

                    b.Property<byte[]>("IdentityPublicKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("identity_public_key");

                    b.Property<DateTimeOffset?>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.Property<DeviceStatus>("Status")
                        .HasColumnType("device_status")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_devices");

                    b.HasIndex("UserId", "ClientDeviceId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_devices_user_id_client_device_id");

                    b.ToTable("user_devices", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.Entities.UserDeviceBackup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<byte[]>("Backup")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("backup");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<string>("ETag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("e_tag");

                    b.Property<int>("RecoveryKeyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("recovery_key_version");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_user_device_backups");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_device_backups_user_id");

                    b.HasIndex("DeviceId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_user_device_backups_device_id_version");

                    b.ToTable("user_device_backups", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.Entities.UserKey", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("Key")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("key");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_id");

                    b.Property<byte[]>("PublicKey")
                        .HasColumnType("bytea")
                        .HasColumnName("public_key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_keys");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_keys_user_id");

                    b.ToTable("user_keys", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.Entities.UserKeyPackage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("CipherSuite")
                        .HasColumnType("integer")
                        .HasColumnName("cipher_suite");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsLastResort")
                        .HasColumnType("boolean")
                        .HasColumnName("is_last_resort");

                    b.Property<byte[]>("KeyPackage")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("key_package");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_key_packages");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_user_key_packages_device_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_key_packages_user_id");

                    b.ToTable("user_key_packages", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.Entities.UserPreferences", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data");

                    b.Property<DirectMessageSettings>("DirectMessageSettings")
                        .HasColumnType("direct_message_settings")
                        .HasColumnName("direct_message_settings");

                    b.Property<PrivacySettings>("PrivacySettings")
                        .HasColumnType("privacy_settings")
                        .HasColumnName("privacy_settings");

                    b.Property<Theme>("Theme")
                        .HasColumnType("theme")
                        .HasColumnName("theme");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_user_preferences");

                    b.ToTable("user_preferences", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.Entities.UserPublicKey", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("public_key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_public_keys");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_public_keys_user_id");

                    b.ToTable("user_public_keys", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.Entities.UserPushToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<PushTokenKind>("Kind")
                        .HasColumnType("push_token_kind")
                        .HasColumnName("kind");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_push_tokens");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_user_push_tokens_device_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_push_tokens_user_id");

                    b.HasIndex("Kind", "Token")
                        .IsUnique()
                        .HasDatabaseName("ix_user_push_tokens_kind_token");

                    b.ToTable("user_push_tokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("asp_net_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("asp_net_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("asp_net_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("asp_net_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("asp_net_user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("asp_net_user_tokens", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("application_type");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("text")
                        .HasColumnName("client_secret");

                    b.Property<string>("ClientType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("client_type");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("concurrency_token");

                    b.Property<string>("ConsentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("consent_type");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text")
                        .HasColumnName("display_names");

                    b.Property<string>("JsonWebKeySet")
                        .HasColumnType("text")
                        .HasColumnName("json_web_key_set");

                    b.Property<string>("Permissions")
                        .HasColumnType("text")
                        .HasColumnName("permissions");

                    b.Property<string>("PostLogoutRedirectUris")
                        .HasColumnType("text")
                        .HasColumnName("post_logout_redirect_uris");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<string>("RedirectUris")
                        .HasColumnType("text")
                        .HasColumnName("redirect_uris");

                    b.Property<string>("Requirements")
                        .HasColumnType("text")
                        .HasColumnName("requirements");

                    b.Property<string>("Settings")
                        .HasColumnType("text")
                        .HasColumnName("settings");

                    b.HasKey("Id")
                        .HasName("pk_open_iddict_applications");

                    b.HasIndex("ClientId")
                        .IsUnique()
                        .HasDatabaseName("ix_open_iddict_applications_client_id");

                    b.ToTable("OpenIddictApplications", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text")
                        .HasColumnName("application_id");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<string>("Scopes")
                        .HasColumnType("text")
                        .HasColumnName("scopes");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("subject");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_open_iddict_authorizations");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type")
                        .HasDatabaseName("ix_open_iddict_authorizations_application_id_status_subject_type");

                    b.ToTable("OpenIddictAuthorizations", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreScope", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("concurrency_token");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Descriptions")
                        .HasColumnType("text")
                        .HasColumnName("descriptions");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text")
                        .HasColumnName("display_names");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<string>("Resources")
                        .HasColumnType("text")
                        .HasColumnName("resources");

                    b.HasKey("Id")
                        .HasName("pk_open_iddict_scopes");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_open_iddict_scopes_name");

                    b.ToTable("OpenIddictScopes", (string)null);
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationId")
                        .HasColumnType("text")
                        .HasColumnName("application_id");

                    b.Property<string>("AuthorizationId")
                        .HasColumnType("text")
                        .HasColumnName("authorization_id");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_date");

                    b.Property<string>("Payload")
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<DateTime?>("RedemptionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redemption_date");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_id");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("subject");

                    b.Property<string>("Type")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_open_iddict_tokens");

                    b.HasIndex("AuthorizationId")
                        .HasDatabaseName("ix_open_iddict_tokens_authorization_id");

                    b.HasIndex("ReferenceId")
                        .IsUnique()
                        .HasDatabaseName("ix_open_iddict_tokens_reference_id");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type")
                        .HasDatabaseName("ix_open_iddict_tokens_application_id_status_subject_type");

                    b.ToTable("OpenIddictTokens", (string)null);
                });

            modelBuilder.Entity("Identity.Domain.Aggregates.ApplicationUser", b =>
                {
                    b.HasOne("Identity.Domain.Entities.UserPreferences", "UserPreferences")
                        .WithOne()
                        .HasForeignKey("Identity.Domain.Aggregates.ApplicationUser", "UserPreferencesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_users_user_preferences_user_preferences_id");

                    b.OwnsOne("Identity.Domain.ValueObjects.EncryptedMasterKey", "EncryptedMasterKey", b1 =>
                        {
                            b1.Property<string>("ApplicationUserId")
                                .HasColumnType("text")
                                .HasColumnName("application_user_id");

                            b1.Property<int>("Argon2Iterations")
                                .HasColumnType("integer")
                                .HasColumnName("argon2iterations");

                            b1.Property<int>("Argon2Memory")
                                .HasColumnType("integer")
                                .HasColumnName("argon2memory");

                            b1.Property<int>("Argon2Parallelism")
                                .HasColumnType("integer")
                                .HasColumnName("argon2parallelism");

                            b1.Property<byte[]>("CipherText")
                                .IsRequired()
                                .HasColumnType("bytea")
                                .HasColumnName("cipher_text");

                            b1.Property<byte[]>("Iv")
                                .IsRequired()
                                .HasColumnType("bytea")
                                .HasColumnName("iv");

                            b1.Property<string>("Kdf")
                                .HasColumnType("text")
                                .HasColumnName("kdf");

                            b1.Property<byte[]>("PublicVerifier")
                                .HasColumnType("bytea")
                                .HasColumnName("public_verifier");

                            b1.Property<byte[]>("Salt")
                                .IsRequired()
                                .HasColumnType("bytea")
                                .HasColumnName("salt");

                            b1.Property<int>("Version")
                                .HasColumnType("integer")
                                .HasColumnName("version");

                            b1.HasKey("ApplicationUserId")
                                .HasName("pk_encrypted_master_key");

                            b1.ToTable("encrypted_master_key");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationUserId")
                                .HasConstraintName("fk_encrypted_master_key_asp_net_users_application_user_id");
                        });

                    b.OwnsOne("Identity.Domain.ValueObjects.EncryptedMasterKey", "RecoveryCodeWrappedMasterKey", b1 =>
                        {
                            b1.Property<string>("ApplicationUserId")
                                .HasColumnType("text")
                                .HasColumnName("id");

                            b1.Property<int>("Argon2Iterations")
                                .HasColumnType("integer")
                                .HasColumnName("recovery_code_wrapped_master_key_argon2iterations");

                            b1.Property<int>("Argon2Memory")
                                .HasColumnType("integer")
                                .HasColumnName("recovery_code_wrapped_master_key_argon2memory");

                            b1.Property<int>("Argon2Parallelism")
                                .HasColumnType("integer")
                                .HasColumnName("recovery_code_wrapped_master_key_argon2parallelism");

                            b1.Property<byte[]>("CipherText")
                                .IsRequired()
                                .HasColumnType("bytea")
                                .HasColumnName("recovery_code_wrapped_master_key_cipher_text");

                            b1.Property<byte[]>("Iv")
                                .IsRequired()
                                .HasColumnType("bytea")
                                .HasColumnName("recovery_code_wrapped_master_key_iv");

                            b1.Property<string>("Kdf")
                                .HasColumnType("text")
                                .HasColumnName("recovery_code_wrapped_master_key_kdf");

                            b1.Property<byte[]>("PublicVerifier")
                                .HasColumnType("bytea")
                                .HasColumnName("recovery_code_wrapped_master_key_public_verifier");

                            b1.Property<byte[]>("Salt")
                                .IsRequired()
                                .HasColumnType("bytea")
                                .HasColumnName("recovery_code_wrapped_master_key_salt");

                            b1.Property<int>("Version")
                                .HasColumnType("integer")
                                .HasColumnName("recovery_code_wrapped_master_key_version");

                            b1.HasKey("ApplicationUserId");

                            b1.ToTable("asp_net_users");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationUserId")
                                .HasConstraintName("fk_asp_net_users_asp_net_users_id");
                        });

                    b.OwnsOne("Identity.Domain.ValueObjects.AgeVerification", "AgeVerification", b1 =>
                        {
                            b1.Property<string>("ApplicationUserId")
                                .HasColumnType("text")
                                .HasColumnName("application_user_id");

                            b1.Property<DateTimeOffset?>("AiEstimationCompletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ai_estimation_completed_at");

                            b1.Property<DateOnly>("BirthDate")
                                .HasColumnType("date")
                                .HasColumnName("birth_date");

                            b1.Property<DateTimeOffset?>("GovermentIdCompletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("goverment_id_completed_at");

                            b1.Property<AgeVertificationLevel>("Level")
                                .HasColumnType("age_vertification_level")
                                .HasColumnName("level");

                            b1.Property<DateTimeOffset?>("SelfDeclarationCompletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("self_declaration_completed_at");

                            b1.HasKey("ApplicationUserId")
                                .HasName("pk_age_verification");

                            b1.ToTable("age_verification");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationUserId")
                                .HasConstraintName("fk_age_verification_asp_net_users_application_user_id");
                        });

                    b.Navigation("AgeVerification")
                        .IsRequired();

                    b.Navigation("EncryptedMasterKey");

                    b.Navigation("RecoveryCodeWrappedMasterKey");

                    b.Navigation("UserPreferences");
                });

            modelBuilder.Entity("Identity.Domain.Entities.IdentityAuditEvent", b =>
                {
                    b.HasOne("Identity.Domain.Aggregates.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_identity_audit_events_asp_net_users_user_id");
                });

            modelBuilder.Entity("Identity.Domain.Entities.LoginSession", b =>
                {
                    b.HasOne("Identity.Domain.Entities.UserDevice", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_login_sessions_user_devices_device_id");

                    b.HasOne("Identity.Domain.Aggregates.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_login_sessions_users_user_id");

                    b.Navigation("Device");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Identity.Domain.Entities.RevokedDeviceCertificate", b =>
                {
                    b.HasOne("Identity.Domain.Aggregates.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_revoked_device_certificates_asp_net_users_user_id");
                });

            modelBuilder.Entity("Identity.Domain.Entities.UserBackupTransfer", b =>
                {
                    b.HasOne("Identity.Domain.Aggregates.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_backup_transfers_asp_net_users_user_id");
                });

            modelBuilder.Entity("Identity.Domain.Entities.UserDevice", b =>
                {
                    b.HasOne("Identity.Domain.Aggregates.ApplicationUser", "User")
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_devices_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Identity.Domain.Entities.UserDeviceBackup", b =>
                {
                    b.HasOne("Identity.Domain.Entities.UserDevice", "Device")
                        .WithMany("Backups")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_device_backups_user_devices_device_id");

                    b.HasOne("Identity.Domain.Aggregates.ApplicationUser", "User")
                        .WithMany("Backups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_device_backups_users_user_id");

                    b.Navigation("Device");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Identity.Domain.Entities.UserKey", b =>
                {
                    b.HasOne("Identity.Domain.Aggregates.ApplicationUser", null)
                        .WithMany("UserKeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_keys_asp_net_users_user_id");
                });

            modelBuilder.Entity("Identity.Domain.Entities.UserKeyPackage", b =>
                {
                    b.HasOne("Identity.Domain.Entities.UserDevice", "Device")
                        .WithMany("KeyPackages")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_key_packages_user_devices_device_id");

                    b.HasOne("Identity.Domain.Aggregates.ApplicationUser", "User")
                        .WithMany("KeyPackages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_user_key_packages_users_user_id");

                    b.Navigation("Device");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Identity.Domain.Entities.UserPublicKey", b =>
                {
                    b.HasOne("Identity.Domain.Aggregates.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_public_keys_asp_net_users_user_id");
                });

            modelBuilder.Entity("Identity.Domain.Entities.UserPushToken", b =>
                {
                    b.HasOne("Identity.Domain.Entities.UserDevice", "Device")
                        .WithMany("PushTokens")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_user_push_tokens_user_devices_device_id");

                    b.HasOne("Identity.Domain.Aggregates.ApplicationUser", "User")
                        .WithMany("PushTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_push_tokens_users_user_id");

                    b.Navigation("Device");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Identity.Domain.Aggregates.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Identity.Domain.Aggregates.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("Identity.Domain.Aggregates.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Identity.Domain.Aggregates.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Authorizations")
                        .HasForeignKey("ApplicationId")
                        .HasConstraintName("fk_open_iddict_authorizations_open_iddict_applications_application");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken", b =>
                {
                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", "Application")
                        .WithMany("Tokens")
                        .HasForeignKey("ApplicationId")
                        .HasConstraintName("fk_open_iddict_tokens_open_iddict_applications_application_id");

                    b.HasOne("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", "Authorization")
                        .WithMany("Tokens")
                        .HasForeignKey("AuthorizationId")
                        .HasConstraintName("fk_open_iddict_tokens_open_iddict_authorizations_authorization_id");

                    b.Navigation("Application");

                    b.Navigation("Authorization");
                });

            modelBuilder.Entity("Identity.Domain.Aggregates.ApplicationUser", b =>
                {
                    b.Navigation("Backups");

                    b.Navigation("Devices");

                    b.Navigation("KeyPackages");

                    b.Navigation("PushTokens");

                    b.Navigation("UserKeys");
                });

            modelBuilder.Entity("Identity.Domain.Entities.UserDevice", b =>
                {
                    b.Navigation("Backups");

                    b.Navigation("KeyPackages");

                    b.Navigation("PushTokens");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreApplication", b =>
                {
                    b.Navigation("Authorizations");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreAuthorization", b =>
                {
                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
