<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Facet.Dashboard" Version="6.6.8" />
        <PackageReference Include="Facet.Extensions" Version="6.6.8" />
        <PackageReference Include="Facet.Extensions.EFCore" Version="6.6.8" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Common" Version="10.0.9" />
        <PackageReference Include="Microsoft.AspNetCore.SignalR.StackExchangeRedis" Version="10.0.9" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.9" />
        <PackageReference Include="RedLock.net" Version="2.3.2" />
        <PackageReference Include="StackExchange.Redis" Version="3.0.0" />
        <PackageReference Include="WolverineFx" Version="6.13.1" />
        <PackageReference Include="WolverineFx.EntityFrameworkCore" Version="6.13.1" />
        <PackageReference Include="WolverineFx.Http" Version="6.13.1" />
        <PackageReference Include="WolverineFx.Postgresql" Version="6.13.1" />
        <PackageReference Include="WolverineFx.RabbitMQ" Version="6.13.1" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
        <None Include="Credentials\**\*">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\AppEnvironment\AppEnvironment.csproj" />
      <ProjectReference Include="..\Guild.Contracts\Guild.Contracts.csproj" />
      <ProjectReference Include="..\Guild.Infrastructure\Guild.Infrastructure.csproj" />
      <ProjectReference Include="..\Messaging.Contracts\Messaging.Contracts.csproj" />
      <ProjectReference Include="..\Messaging.Domain\Messaging.Domain.csproj" />
      <ProjectReference Include="..\Messaging\Messaging.csproj" />
      <ProjectReference Include="..\Social.Contracts\Social.Contracts.csproj" />
    </ItemGroup>

</Project>
