// <auto-generated />
using System;
using Echo.Persistence.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Echo.Persistence.Migrations
{
    [DbContext(typeof(MicroserviceContext))]
    [Migration("20260805070414_AddModerationAndSupport")]
    partial class AddModerationAndSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Echo.Domain.Entities.EchoConfiguration", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EnforcedSingleton")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("enforced_singleton");

                    b.Property<bool>("IsLoginEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_login_enabled");

                    b.Property<bool>("IsRegisterEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_register_enabled");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_echo_configurations");

                    b.HasIndex("EnforcedSingleton")
                        .IsUnique()
                        .HasDatabaseName("ix_echo_configurations_enforced_singleton");

                    b.ToTable("echo_configurations", null, t =>
                        {
                            t.HasCheckConstraint("ck_single_row_enforcer", "enforced_singleton = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = "ecco_3FQmtSXdg2VUCabuTR1r25imW2m",
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EnforcedSingleton = 1,
                            IsLoginEnabled = true,
                            IsRegisterEnabled = true,
                            UpdatedAt = new DateTimeOffset(new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Echo.Domain.Entities.Moderation.ModerationAction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ActorUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("InternalNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("internal_note");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("PublicNote")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("public_note");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("reason");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("reference");

                    b.Property<string>("ReportId")
                        .HasColumnType("text")
                        .HasColumnName("report_id");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("revocation_reason");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedByUserId")
                        .HasColumnType("text")
                        .HasColumnName("revoked_by_user_id");

                    b.Property<string>("TargetUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_user_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_moderation_actions");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_moderation_actions_actor_user_id");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasDatabaseName("ix_moderation_actions_reference");

                    b.HasIndex("TargetUserId")
                        .HasDatabaseName("ix_moderation_actions_target_user_id");

                    b.HasIndex("TargetUserId", "Kind", "RevokedAt", "ExpiresAt")
                        .HasDatabaseName("ix_moderation_actions_target_user_id_kind_revoked_at_expires_at");

                    b.ToTable("moderation_actions", (string)null);
                });

            modelBuilder.Entity("Echo.Domain.Entities.Moderation.ModerationAppeal", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ActionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("contact_email");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<string>("DecidedByUserId")
                        .HasColumnType("text")
                        .HasColumnName("decided_by_user_id");

                    b.Property<string>("DecisionNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("decision_note");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("SubmittedByUserId")
                        .HasColumnType("text")
                        .HasColumnName("submitted_by_user_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_moderation_appeals");

                    b.HasIndex("ActionId")
                        .IsUnique()
                        .HasDatabaseName("ix_moderation_appeals_action_id");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasDatabaseName("ix_moderation_appeals_reference");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_moderation_appeals_status_created_at");

                    b.ToTable("moderation_appeals", (string)null);
                });

            modelBuilder.Entity("Echo.Domain.Entities.Moderation.ModerationAuditEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<string>("ActorUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Detail")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("detail");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<string>("SubjectId")
                        .HasColumnType("text")
                        .HasColumnName("subject_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_moderation_audit_entries");

                    b.HasIndex("ActorUserId", "CreatedAt")
                        .HasDatabaseName("ix_moderation_audit_entries_actor_user_id_created_at");

                    b.HasIndex("SubjectId", "CreatedAt")
                        .HasDatabaseName("ix_moderation_audit_entries_subject_id_created_at");

                    b.ToTable("moderation_audit_entries", (string)null);
                });

            modelBuilder.Entity("Echo.Domain.Entities.Moderation.ModerationReport", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AssignedToUserId")
                        .HasColumnType("text")
                        .HasColumnName("assigned_to_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("details");

                    b.Property<int>("DuplicateCount")
                        .HasColumnType("integer")
                        .HasColumnName("duplicate_count");

                    b.Property<string>("DuplicateOfId")
                        .HasColumnType("text")
                        .HasColumnName("duplicate_of_id");

                    b.Property<string>("EvidenceJson")
                        .HasMaxLength(16384)
                        .HasColumnType("character varying(16384)")
                        .HasColumnName("evidence_json");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("priority");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("reason");

                    b.Property<string>("ReporterUserId")
                        .HasColumnType("text")
                        .HasColumnName("reporter_user_id");

                    b.Property<string>("Resolution")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("resolution");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ResolvedByUserId")
                        .HasColumnType("text")
                        .HasColumnName("resolved_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("SubjectId")
                        .HasColumnType("text")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("subject_kind");

                    b.Property<string>("TargetUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_user_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_moderation_reports");

                    b.HasIndex("AssignedToUserId")
                        .HasDatabaseName("ix_moderation_reports_assigned_to_user_id");

                    b.HasIndex("ReporterUserId")
                        .HasDatabaseName("ix_moderation_reports_reporter_user_id");

                    b.HasIndex("TargetUserId")
                        .HasDatabaseName("ix_moderation_reports_target_user_id");

                    b.HasIndex("Status", "Priority", "CreatedAt")
                        .HasDatabaseName("ix_moderation_reports_status_priority_created_at");

                    b.HasIndex("ReporterUserId", "SubjectKind", "SubjectId", "CreatedAt")
                        .HasDatabaseName("ix_moderation_reports_reporter_user_id_subject_kind_subject_id");

                    b.ToTable("moderation_reports", (string)null);
                });

            modelBuilder.Entity("Echo.Domain.Entities.Moderation.SupportTicket", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<byte[]>("AccessTokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("access_token_hash");

                    b.Property<string>("AssignedToUserId")
                        .HasColumnType("text")
                        .HasColumnName("assigned_to_user_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("contact_email");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("reference");

                    b.Property<string>("RequesterUserId")
                        .HasColumnType("text")
                        .HasColumnName("requester_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_support_tickets");

                    b.HasIndex("AssignedToUserId")
                        .HasDatabaseName("ix_support_tickets_assigned_to_user_id");

                    b.HasIndex("ContactEmail")
                        .HasDatabaseName("ix_support_tickets_contact_email");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasDatabaseName("ix_support_tickets_reference");

                    b.HasIndex("Status", "LastActivityAt")
                        .HasDatabaseName("ix_support_tickets_status_last_activity_at");

                    b.ToTable("support_tickets", (string)null);
                });

            modelBuilder.Entity("Echo.Domain.Entities.Moderation.SupportTicketMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AuthorKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("author_kind");

                    b.Property<string>("AuthorUserId")
                        .HasColumnType("text")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_internal");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticket_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_support_ticket_messages");

                    b.HasIndex("TicketId", "CreatedAt")
                        .HasDatabaseName("ix_support_ticket_messages_ticket_id_created_at");

                    b.ToTable("support_ticket_messages", (string)null);
                });

            modelBuilder.Entity("Echo.Domain.Entities.Moderation.ModerationAppeal", b =>
                {
                    b.HasOne("Echo.Domain.Entities.Moderation.ModerationAction", "Action")
                        .WithMany("Appeals")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_moderation_appeals_moderation_actions_action_id");

                    b.Navigation("Action");
                });

            modelBuilder.Entity("Echo.Domain.Entities.Moderation.SupportTicketMessage", b =>
                {
                    b.HasOne("Echo.Domain.Entities.Moderation.SupportTicket", "Ticket")
                        .WithMany("Messages")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_support_ticket_messages_support_tickets_ticket_id");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Echo.Domain.Entities.Moderation.ModerationAction", b =>
                {
                    b.Navigation("Appeals");
                });

            modelBuilder.Entity("Echo.Domain.Entities.Moderation.SupportTicket", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
