<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Domain\Domain.csproj" />
      <ProjectReference Include="..\Persistence\Persistence.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="ChatAIze.PerfectEmail" Version="0.4.0" />
      <PackageReference Include="FluentValidation" Version="12.1.1" />
      <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="10.0.9" />
    </ItemGroup>

</Project>
