// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Social.Domain.Enums;
using Social.Infrastructure.Persistence;

#nullable disable

namespace Social.Infrastructure.Migrations
{
    [DbContext(typeof(MicroserviceContext))]
    [Migration("20260425184205_RelatedShallBeNullable")]
    partial class RelatedShallBeNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "relationship_status", new[] { "blocked", "friends", "none", "pending_incoming", "pending_outgoing" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Social.Domain.Aggregate.Profile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Hash")
                        .HasColumnType("integer")
                        .HasColumnName("hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_profiles");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("Social.Domain.Aggregate.Relationship", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_id");

                    b.Property<string>("RelatedId")
                        .HasColumnType("text")
                        .HasColumnName("related_id");

                    b.Property<RelationshipStatus>("Status")
                        .HasColumnType("relationship_status")
                        .HasColumnName("status");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_relationships");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_relationships_owner_id");

                    b.HasIndex("RelatedId")
                        .IsUnique()
                        .HasDatabaseName("ix_relationships_related_id");

                    b.HasIndex("TargetId")
                        .HasDatabaseName("ix_relationships_target_id");

                    b.ToTable("relationships", (string)null);
                });

            modelBuilder.Entity("Social.Domain.Aggregate.Relationship", b =>
                {
                    b.HasOne("Social.Domain.Aggregate.Profile", "Owner")
                        .WithMany("Relationships")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_relationships_profiles_owner_id");

                    b.HasOne("Social.Domain.Aggregate.Relationship", "Related")
                        .WithOne()
                        .HasForeignKey("Social.Domain.Aggregate.Relationship", "RelatedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_relationships_relationships_related_id");

                    b.HasOne("Social.Domain.Aggregate.Profile", "Target")
                        .WithMany("InvolvedRelationships")
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_relationships_profiles_target_id");

                    b.Navigation("Owner");

                    b.Navigation("Related");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("Social.Domain.Aggregate.Profile", b =>
                {
                    b.Navigation("InvolvedRelationships");

                    b.Navigation("Relationships");
                });
#pragma warning restore 612, 618
        }
    }
}
